### ISSUE TITLE
Pyinstaller-3.4 fails to build on Alpine 3.5, 3.7 (bootloader issue)

### ISSUE THREAD

**Issue by DevOpsJon** [six8/pyinstaller-alpine#4]
I wonder if this project is still active/maintained?

I tried to build it recently and got the following errors. I wonder if anyone else found a workaround yet? I put details here:

https://github.com/pyinstaller/pyinstaller/issues/4196

**Comment by six8** [comment]
It's still in use. But I haven't tried with the latest PyInstaller in a while.

I'll see if I can reproduce it.

**Comment by brezerk** [comment]
yeah. stepped on this as a part of playing around #5 https://circleci.com/gh/brezerk/pyinstaller-alpine/10

**Comment by brezerk** [comment]
it looks like it is related to GCC 8. It is treating `strncat` warning as an error:

>Apparently GCC understands that strncat(_tempname, "/hellooXXXXXX", 13); is no different from >strcat(_tempname, "/hellooXXXXXX");, and finds it suspicious that you're using former instead of the >latter.
>
>If you can change the code, use strcat instead (or even better, rewrite the thing to use std::string).
>
>If you can't change the code, use -Wno-stringop-overflow flag to disable the warning.

**Comment by brezerk** [comment]
@DevOpsJon can you test it now? I think it should be resolved :)

**Comment by alexks02** [comment]
@brezerk I can do it! (-;
P.S. Доброго времени суток!)
