### ISSUE TITLE
Docker images for ARM32v7 and ARM64v8

### ISSUE THREAD

**Issue by brezerk** [six8/pyinstaller-alpine#5]
hi

I am trying to build `kubeyaml` and `flux` docker images for arm arch and `six8/pyinstaller-alpine` image seems to be a blocker at this point :)

Would it be possible for you to provide official docker images for ARM32v7 and ARM64v8 please?

If you are interested in -- I can help with adopting `binfmt_misc` approach used by prometheus https://github.com/prometheus/prometheus/pull/5031 to build multiarch images using circleci CI/CD tool (you may find it useful for project automation btw)

**Comment by six8** [comment]
Good idea. Your help would be appreciated.

**Comment by brezerk** [comment]
hi @six8 

Would you be able to start providing official docker images for ARM32v7 and ARM64v8 by adopting CircleCI as described at #6 please?

**Comment by six8** [comment]
Done. https://hub.docker.com/u/six8

Thanks!

**Comment by brezerk** [comment]
Thanks a ton!
